server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: local
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8071/
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true